In [32]:
import numpy as np
import sklearn 
from sklearn.neighbors import KDTree
from sklearn.ensemble import RandomForestClassifier
import time
from sklearn import metrics
import pandas as pd
from sklearn.externals import joblib

In [33]:
# Define NN size 
NN = 100

## Load in all data

After calculating the overall accuracy, I will not work with the training dataset anymore, but only test it on the testing dataset. 

In [34]:
# Uploadng my datasets
# Define a data frame with all my data# Define  
FILE_PATH = r"../DATA/ML_datasets/Initial_setup"
META_FILE_PATH = "../DATA/META"
IMAGE_FILE_PATH = r"images"

# Testing data
y_test = np.loadtxt(FILE_PATH+'/y_test_'+ str(NN) +'NN.txt', delimiter=',')
X_test = np.loadtxt(FILE_PATH+'/X_test_'+ str(NN) +'NN.txt', delimiter=',')

In [35]:
# For RF classifier: cast as float32 
y_test = y_test.astype('float32')
X_test = X_test.astype('float32')

In [36]:
###uploading the saved classifier
filename = '/randomforest_model_'+ str(NN) +'NN.sav'
clf = joblib.load(FILE_PATH + filename)

In [37]:
# Load the predictions
predictions_train = np.loadtxt(FILE_PATH+'/predictions_train_'+ str(NN) +'NN.txt', delimiter=',')
predictions_test = np.loadtxt(FILE_PATH+'/predictions_test_'+ str(NN) +'NN.txt', delimiter=',')

## Now start evaluation 

### Show problem with threshold or unclassified

I thought I could determine a threshold or a difference between two values to create a class unclassified. But this will not work. Especially the predictions for the noisy and small classes are really bad. They are never the highest in the probability array. Mostly, they get classified as building. Even if I set a threshold, the classsifier is still sure that it must be a building. Also, there is a biggap to the next highest value. 

In [ ]:
# Calculate all probabilities for the testing set 
probability_array = clf.predict_proba(X_test)
print "This is the shape of the array", probability_array.shape

In [65]:
probability_array.sort()
print "Max", (probability_array[0][-1])*100, "%"
print "sec Max", (probability_array[0][-2])*100, "%"
print "Difference between highest and second highest value", (probability_array[0][-1])*100 - (probability_array[0][-2])*100, "%"

Max 90.59667185706162 %
sec Max 4.1939604148964955 %
Difference between highest and second highest value 86.40271144216513 %


In [68]:
# Number of instances per class in testing set  
np.histogram(y_test)

(array([ 646126,  176841,   11971, 1271960,     768,    3605,    4614,
           7960,   63779,   22835]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [40]:
# Look where the value should be class 11 (potted plant)
np.where(y_test == 11)

In [69]:
# For these values, check the probability 
probability_array[2209993]

array([6.27756543e-04, 3.30485854e-03, 4.92809204e-03, 4.95491760e-03,
       9.05750052e-03, 9.53493209e-03, 1.51425102e-02, 1.85366707e-02,
       2.27663613e-02, 1.23530836e-01, 7.87615564e-01])

In [80]:
for i in range(0,11):
    print "Max. value for class " +str(i+1)+ ":", probability_array[:,i].max()*100, "%"


Max. value for class 1: 0.3699568958628669 %
Max. value for class 2: 0.6751852446548976 %
Max. value for class 3: 1.0076837122626885 %
Max. value for class 4: 1.7199943004976337 %
Max. value for class 5: 2.051003130842827 %
Max. value for class 6: 5.377239347152576 %
Max. value for class 7: 11.36167740470613 %
Max. value for class 8: 22.72579506396993 %
Max. value for class 9: 31.249614158660265 %
Max. value for class 10: 49.00685656977799 %
Max. value for class 11: 96.53842574048637 %


In [84]:
probability_array[:,0].shape

(2210459,)